### ISSUE TITLE
Worked on localhost, 500 server error on production

### ISSUE THREAD

**Issue by thomasrye** [adjdred/html2canvas-proxy-php#2]
I'm assuming it has something to do with my server's settings, but I don't know what it would be. Any advice would be greatly appreciated.

**Comment by adjdred** [comment]
Do you have curl enabled on your server?

**Comment by thomasrye** [comment]
I do. I use curl via php for some other things on my site.

**Comment by thomasrye** [comment]
Closed by 6571944
